--- #YAML:1.0
name:                     Labyrinth::Plugin::Event
version:                  1.00
abstract:                 Events plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  Labyrinth:	                            5.04
  Labyrinth::Plugin::Articles::Sections:  5.06
  Clone:                                  0
  Time::Local:                            0
recommends:
  Test::More:                             0.70
  Test::Pod:                              1.00
  Test::Pod::Coverage:                    0.08
  Test::CPAN::Meta:                       0.13
  Test::CPAN::Meta::JSON:                 0.10
build_requires:
  Test::More:                             0.01

provides:
  Labyrinth::Plugin::Event:
    file:     lib/Labyrinth/Plugin/Event.pm
    version:  1.00
  Labyrinth::Plugin::Event::Sponsors:
    file:     lib/Labyrinth/Plugin/Event/Sponsors.pm
    version:  1.00
  Labyrinth::Plugin::Event::Talks:
    file:     lib/Labyrinth/Plugin/Event/Talks.pm
    version:  1.00
  Labyrinth::Plugin::Event::Types:
    file:     lib/Labyrinth/Plugin/Event/Types.pm
    version:  1.00
  Labyrinth::Plugin::Event::Venues:
    file:     lib/Labyrinth/Plugin/Event/Venues.pm
    version:  1.00

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  license:    http://dev.perl.org/licenses/
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-Event

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
